openapi: 3.1.0
info:
  version: 1.0.0
  title: Simple example API
  description: An API to illustrate Swagger

paths:

  /health:
    get:
      description: Health route
      responses:
        '200':
          description: Successful response 

  /conversation:
    get:
      description: Get information about a conversation
      parameters:
        - in: query
          name: id
          schema:
            type: number
          description: Get conversation by id
      responses:
        '200':
          description: Successful response 
    post:
      description: Add a new conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title associated with the conversation
                description:
                  type: string
                  description: The description associated with the conversation
              required:
                - name
      responses:
        '200':
          description: Successful response 
